const QUIZZES_ACTION_TYPES = {
  FETCH_QUIZZES_BY_CATEGORY_START: 'quizzes/FETCH_QUIZZES_BY_CATEGORY_START',
  FETCH_QUIZZES_BY_CATEGORY_SUCCESS: 'quizzes/FETCH_QUIZZES_BY_CATEGORY_SUCCESS',
  FETCH_QUIZZES_BY_CATEGORY_FAILED: 'quizzes/FETCH_QUIZZES_BY_CATEGORY_FAILED',
};

export default QUIZZES_ACTION_TYPES;