const QUESTIONS_ACTION_TYPES = {
  FETCH_QUESTIONS_BY_QUIZ_START: 'questions/FETCH_QUESTIONS_BY_QUIZ_START',
  FETCH_QUESTIONS_BY_QUIZ_SUCCESS: 'questions/FETCH_QUESTIONS_BY_QUIZ_SUCCESS',
  FETCH_QUESTIONS_BY_QUIZ_FAILED: 'questions/FETCH_QUESTIONS_BY_QUIZ_FAILED',
};

export default QUESTIONS_ACTION_TYPES;